### ISSUE TITLE
NestedText.NET

### ISSUE THREAD

**Issue by MichalMarsalek** [KenKundert/nestedtext#51]
Hello again. I just finished a [.NET NestedText library](https://www.nuget.org/packages/NestedText/1.0.0).
In addition to dumping/loading (serializing/deserializing as it is usually called in .NET), the library includes a customizable formatter.

It passes all the official tests, except for two (`inline_dict_20`, `inline_dict_22`) for which I am explicitly skipping the validation of the error messages as I believe the expectation is inconsistent/incorrect. For reasons I don't understand, the expectations are just `"expected value"`, instead of the usual form `"expected ':', found '}'"`, which my library reports. This is all the more strange that the `inline_dict_21` case differs only by whitespace (which is insignificant unless inside a string value), yet there, the expectation is `"expected ':', found '}'"`.

**Comment by KenKundert** [comment]
Don't feel that you need to match the error messages given in the load_err.json files.  They are meant to be suggestive rather than prescriptive.

As for why 20 and 22 differ from 21, in 20 and 22 there is nothing after the comma, so the python implementation takes that as no value being given.  In 21 something does follow the comma, a space, so the python implementation interprets that as user starting to give a value, but not completing it.  That is why the error messages differ.  But your interpretation is equally valid.

**Comment by MichalMarsalek** [comment]
> They are meant to be suggestive rather than prescriptive.

Cool. I opened a PR for linking the library in the docs.
