### ISSUE TITLE
Empty collections cannot be round-tripped

### ISSUE THREAD

**Issue by dbowring** [KenKundert/nestedtext#8]
```python
>>> import json
>>> import nestedtext as nt
>>> import yaml

>>> empty_dict = {}
>>> json.loads(json.dumps(empty_dict)) == empty_dict
True
>>> yaml.load(yaml.dump(empty_dict)) == empty_dict
True
>>> nt.loads(nt.dumps(empty_dict)) == empty_dict
False

>>> empty_list = []
>>> json.loads(json.dumps(empty_list)) == empty_list
True
>>> yaml.load(yaml.dump(empty_list)) == empty_list
True
>>> nt.loads(nt.dumps(empty_list)) == empty_list
False


>>> sample_data = {"links": {}, "tags": []}
>>> nt.dumps(sample_data)
'links:\n\ntags:\n'
>>> nt.loads(_)
{'links': '', 'tags': ''}
```

Very interested in this as a yaml alternative, but this would be a blocker for me.

**Comment by yunruse** [comment]
In other words, what _would_ return falsy dicts and lists instead returns `None`.

This has... some legitimacy: all of `[], {}, None` are falsy, so `namedtext.load(...) or default` should be fine. However `dict.update` and other methods would be a little bit of a headache here.

I would therefore recommend the data type be as given, with `None` _only_ for falsy input eg `nestedtext.loads('')`.

**Comment by KenKundert** [comment]
This looks like a bug in dump. Give me some time to look into it.

**Comment by KenKundert** [comment]
Upon further review, this is not a bug at all. Rather it is a rather unexpected consequence of the design decision that all leaf values must be strings. At the moment I don't see that changing.

The current behavior of _NestedText_ is consisted with the idea that you use _NestedText_ files to hold the values without any information about the type of those values. Instead it is up to the end application to know what type to expect for a particular value and do the conversion itself. Fortunately, one can use [_voluptuous_](https://pypi.org/project/voluptuous) to do easily do the conversion.

It turns out that this report did uncover a bug. _dump_() should not allow empty dictionaries and lists when _default_='strict' is specified. That will be corrected.
